name: evalbench-grpc-route
hostnames:
- evalbench
meshes:
- projects/898603957982/locations/global/meshes/direct-google-access-evalbench-mesh
rules:
- action:
    destinations:
    - serviceName: projects/898603957982/locations/global/backendServices/evalbench-directpath-bs