dataset_config: https://dar-internal.googlesource.com/nl2code-dataset/cymbalshop-spring/dataset.json
ragl_context_config: https://dar-internal.googlesource.com/nl2code-dataset/cymbalshop-spring/context/ragl_snippets.json
database_config: configs/db/nl2code_postgres.yaml
model_config: configs/model/base_nl2code_model.yaml
prompt_generator: 'NOOPGenerator'
eval_ids: []
scorers: 