apiVersion: v1
kind: ServiceAccount
metadata:
  name: evalbench-ksa
  namespace: evalbench-namespace
  annotations:
    iam.gke.io/gcp-service-account: "evalbench@astana-evaluation.iam.gserviceaccount.com"
