db: postgres
project_id: astana-evaluation
region: us-central1
instance_name: nl2code
database_name: cymbalShop
user_name: app
password: "projects/393137573/secrets/cymbalshop-app-password/versions/1"
